import type { Character } from "./types";

export const CHARACTERS: readonly Character[] = [
  { id: "mario", name_en: "Mario", name_ja: "マリオ" },
  { id: "donkey_kong", name_en: "Donkey Kong", name_ja: "ドンキーコング" },
  { id: "link", name_en: "Link", name_ja: "リンク" },
  { id: "samus", name_en: "Samus", name_ja: "サムス" },
  { id: "dark_samus", name_en: "Dark Samus", name_ja: "ダークサムス" },
  { id: "yoshi", name_en: "Yoshi", name_ja: "ヨッシー" },
  { id: "kirby", name_en: "Kirby", name_ja: "カービィ" },
  { id: "fox", name_en: "Fox", name_ja: "フォックス" },
  { id: "pikachu", name_en: "Pikachu", name_ja: "ピカチュウ" },
  { id: "luigi", name_en: "Luigi", name_ja: "ルイージ" },
  { id: "ness", name_en: "Ness", name_ja: "ネス" },
  { id: "captain_falcon", name_en: "Captain Falcon", name_ja: "キャプテン・ファルコン" },
  { id: "jigglypuff", name_en: "Jigglypuff", name_ja: "プリン" },
  { id: "peach", name_en: "Peach", name_ja: "ピーチ" },
  { id: "daisy", name_en: "Daisy", name_ja: "デイジー" },
  { id: "bowser", name_en: "Bowser", name_ja: "クッパ" },
  { id: "ice_climbers", name_en: "Ice Climbers", name_ja: "アイスクライマー" },
  { id: "sheik", name_en: "Sheik", name_ja: "シーク" },
  { id: "zelda", name_en: "Zelda", name_ja: "ゼルダ" },
  { id: "dr_mario", name_en: "Dr. Mario", name_ja: "ドクターマリオ" },
  { id: "pichu", name_en: "Pichu", name_ja: "ピチュー" },
  { id: "falco", name_en: "Falco", name_ja: "ファルコ" },
  { id: "marth", name_en: "Marth", name_ja: "マルス" },
  { id: "lucina", name_en: "Lucina", name_ja: "ルキナ" },
  { id: "young_link", name_en: "Young Link", name_ja: "こどもリンク" },
  { id: "ganondorf", name_en: "Ganondorf", name_ja: "ガノンドロフ" },
  { id: "mewtwo", name_en: "Mewtwo", name_ja: "ミュウツー" },
  { id: "roy", name_en: "Roy", name_ja: "ロイ" },
  { id: "chrom", name_en: "Chrom", name_ja: "クロム" },
  { id: "mr_game_and_watch", name_en: "Mr. Game & Watch", name_ja: "Mr.ゲーム&ウォッチ" },
  { id: "meta_knight", name_en: "Meta Knight", name_ja: "メタナイト" },
  { id: "pit", name_en: "Pit", name_ja: "ピット" },
  { id: "dark_pit", name_en: "Dark Pit", name_ja: "ブラックピット" },
  { id: "zero_suit_samus", name_en: "Zero Suit Samus", name_ja: "ゼロスーツサムス" },
  { id: "wario", name_en: "Wario", name_ja: "ワリオ" },
  { id: "snake", name_en: "Snake", name_ja: "スネーク" },
  { id: "ike", name_en: "Ike", name_ja: "アイク" },
  { id: "pokemon_trainer", name_en: "Pokemon Trainer", name_ja: "ポケモントレーナー" },
  { id: "diddy_kong", name_en: "Diddy Kong", name_ja: "ディディーコング" },
  { id: "lucas", name_en: "Lucas", name_ja: "リュカ" },
  { id: "sonic", name_en: "Sonic", name_ja: "ソニック" },
  { id: "king_dedede", name_en: "King Dedede", name_ja: "デデデ" },
  { id: "olimar", name_en: "Olimar", name_ja: "ピクミン&オリマー" },
  { id: "lucario", name_en: "Lucario", name_ja: "ルカリオ" },
  { id: "rob", name_en: "R.O.B.", name_ja: "ロボット" },
  { id: "toon_link", name_en: "Toon Link", name_ja: "トゥーンリンク" },
  { id: "wolf", name_en: "Wolf", name_ja: "ウルフ" },
  { id: "villager", name_en: "Villager", name_ja: "むらびと" },
  { id: "mega_man", name_en: "Mega Man", name_ja: "ロックマン" },
  { id: "wii_fit_trainer", name_en: "Wii Fit Trainer", name_ja: "Wii Fit トレーナー" },
  { id: "rosalina", name_en: "Rosalina & Luma", name_ja: "ロゼッタ&チコ" },
  { id: "little_mac", name_en: "Little Mac", name_ja: "リトル・マック" },
  { id: "greninja", name_en: "Greninja", name_ja: "ゲッコウガ" },
  { id: "palutena", name_en: "Palutena", name_ja: "パルテナ" },
  { id: "pac_man", name_en: "Pac-Man", name_ja: "パックマン" },
  { id: "robin", name_en: "Robin", name_ja: "ルフレ" },
  { id: "shulk", name_en: "Shulk", name_ja: "シュルク" },
  { id: "bowser_jr", name_en: "Bowser Jr.", name_ja: "クッパJr." },
  { id: "duck_hunt", name_en: "Duck Hunt", name_ja: "ダックハント" },
  { id: "ryu", name_en: "Ryu", name_ja: "リュウ" },
  { id: "ken", name_en: "Ken", name_ja: "ケン" },
  { id: "cloud", name_en: "Cloud", name_ja: "クラウド" },
  { id: "corrin", name_en: "Corrin", name_ja: "カムイ" },
  { id: "bayonetta", name_en: "Bayonetta", name_ja: "ベヨネッタ" },
  { id: "inkling", name_en: "Inkling", name_ja: "インクリング" },
  { id: "ridley", name_en: "Ridley", name_ja: "リドリー" },
  { id: "simon", name_en: "Simon", name_ja: "シモン" },
  { id: "richter", name_en: "Richter", name_ja: "リヒター" },
  { id: "king_k_rool", name_en: "King K. Rool", name_ja: "キングクルール" },
  { id: "isabelle", name_en: "Isabelle", name_ja: "しずえ" },
  { id: "incineroar", name_en: "Incineroar", name_ja: "ガオガエン" },
  { id: "piranha_plant", name_en: "Piranha Plant", name_ja: "パックンフラワー" },
  { id: "joker", name_en: "Joker", name_ja: "ジョーカー" },
  { id: "hero", name_en: "Hero", name_ja: "勇者" },
  { id: "banjo_kazooie", name_en: "Banjo & Kazooie", name_ja: "バンジョー&カズーイ" },
  { id: "terry", name_en: "Terry", name_ja: "テリー" },
  { id: "byleth", name_en: "Byleth", name_ja: "ベレト/ベレス" },
  { id: "min_min", name_en: "Min Min", name_ja: "ミェンミェン" },
  { id: "steve", name_en: "Steve", name_ja: "スティーブ" },
  { id: "sephiroth", name_en: "Sephiroth", name_ja: "セフィロス" },
  { id: "pyra_mythra", name_en: "Pyra / Mythra", name_ja: "ホムラ/ヒカリ" },
  { id: "kazuya", name_en: "Kazuya", name_ja: "カズヤ" },
  { id: "sora", name_en: "Sora", name_ja: "ソラ" },
  { id: "mii_brawler", name_en: "Mii Brawler", name_ja: "Mii 格闘タイプ" },
  { id: "mii_swordfighter", name_en: "Mii Swordfighter", name_ja: "Mii 剣術タイプ" },
  { id: "mii_gunner", name_en: "Mii Gunner", name_ja: "Mii 射撃タイプ" },
] as const;
